### ISSUE TITLE
are my targets correct?

### ISSUE THREAD

**Issue by timm** [department-of-reuse/DoR#374]
https://github.com/department-of-reuse/DoR/blob/main/workflow/targetted_venues.md

please check

**Comment by neilernst** [comment]
I think so - we could make a tiered / prioritized approach, ICSE/ASE/FSE, followed by ICSME etc. I think we talked about this before but some out of band samples would be interesting to pull in weird outliers (e.g., CAISE, ICSOB, MISQ, ICML)

**Comment by timm** [comment]
- complete 2020
- move on to 2021
